config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations" }

  root 'welcome#show'


  resources :users

  resources :events do
    resources :posts, shallow: true do
      resources :comments, shallow: true
    end
    resources :applications
  end

  post 'events/:id/participants/new' => 'events#add_participant', as: :participant
  delete 'events/:id/participants/:participant_id' => 'events#delete_participant', as: :delete_participant
  get 'events/:id/participants' => 'events#show_participants', as: :participants
  get 'users/:id/applications' => 'users#show_applications', as: :user_applications

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :created_events, class_name: "Event"
  has_many :participants
  has_many :events, through: :participants
  has_many :applications
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :define_user
  def show
  end

  def show_applications
    @applications = @user.applications
  end

  def define_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h3><%=@user.first_name + " " + @user.last_name%></h3>
<label>Город: <%= @user.city %></label>
<label>О себе: <%= @user.info %></label>
<hr/>

app/views/users/show_applications.html.erb
<h2>Мои заявки</h2>
<% if @applications.any? %>
    <% @applications.each do |application| %>
        <div class="post">
          <%= render application %>
          <label>
            <%= link_to 'Редактировать', edit_event_application_path(application.event, application) %> |
            <%= link_to 'Удалить', event_application_path(application.event, application), method: :delete, confirm: 'Вы точно хотите удалить заявку?' %>
          </label>
        </div>
    <% end %>
<% else %>
    <label>Похоже у вас пока нет заявок. <%= link_to 'Найти подходящую конференцию', events_path%></label>

<% end %>