config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations" }

  root 'welcome#show'


  resources :users

  resources :events do
    resources :posts, shallow: true do
      resources :comments, shallow: true
    end
    resources :applications
  end

  post 'events/:id/participants/new' => 'events#add_participant', as: :participant
  delete 'events/:id/participants/:participant_id' => 'events#delete_participant', as: :delete_participant
  get 'events/:id/participants' => 'events#show_participants', as: :participants
  get 'users/:id/applications' => 'users#show_applications', as: :user_applications

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :participants
  has_many :users, through: :participants
  has_many :posts
  has_many :applications
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :define_event, except: [:new, :create, :index]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_author, only: [:edit, :update,:delete, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user

    if @event.save
      redirect_to @event, notice: "Конференция успешно создана"
    else
      redirect_to "/", notice: "При создании конференции возникли проблемы"
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @events = Event.all
  end

  def show
    @user = @event.creator
    @posts = @event.posts.all
    @post = @event.posts.build
  end

  def delete
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: 'Конференция была успешно удалена' }
      format.json { head :no_content }
    end
  end

  def add_participant
    @participant = Participant.new
    @participant.user = current_user
    @participant.event = @event
    @participant.save
    redirect_to @event
  end

  def show_participants
    if @event.creator != current_user
      redirect_to @event
    end
    @participants = @event.participants
  end

  def delete_participant
    @user = User.find(params[:participant_id])
    @participant = Participant.find_by(user_id: @user.id, event_id: params[:id])
    @participant.destroy
    redirect_to @event
  end

  private
  def define_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :date, :begin_time, :end_time,
                                  :city, :address, :description)
  end

  def is_author
    if @event.creator.id != current_user.id
      redirect_to @event
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="event">
  <h4><%= link_to event.name, event_path(event) %></h4>
  <label>Участников: <%= event.users.count %></label>
  <label><%= event.city %>, <%= I18n.localize event.date, format: :long %></label>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>

    <div class="field">
      <%= f.label "Название" %><br/>
      <%= f.text_field :name, autofocus: true, required: true %>
    </div>

    <div class="field">
      <%= f.label "Дата проведения" %><br/>
      <%= f.date_field :date, start_year: Date.today.year, end_year: Date.today.year + 2, required: true %>
    </div>
    <div class="row">
      <div class="large-4 columns">
        <div class="field">
          <%= f.label "Начало" %><br/>
          <%= f.time_field :begin_time %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="large-4 columns">
        <div class="field">
          <%= f.label "Завершение" %><br/>
          <%= f.time_field :end_time %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label "Город" %><br/>
      <%= f.text_field :city, required: true %>
    </div>

    <div class="field">
      <%= f.label "Адрес проведения" %><br/>
      <%= f.text_field :address %>
    </div>

    <div class="field">
      <%= f.label "Описание" %><br/>
      <%= f.text_area :description%>
    </div>

    <div class="actions">
      <%= f.submit "Создать", class: "button" %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h3>Редактирование конференции</h3>
<div class="edit_event">
    <%= render "events/form" %>
</div>

app/views/events/index.html.erb
<% if user_signed_in? %>
    <%= link_to "Создать конференцию", new_event_path, class: "button small", style: "margin-top: 10px" %>
<% end %>

<% @events.reverse_order.each do |event| %>
    <%= render event %>
<% end %>

app/views/events/new.html.erb
<h2>Конференция</h2>
<%= render "events/form" %>

app/views/events/show.html.erb
<h4><%= @event.name %></h4>
<label>Город: <%= @event.city %></label>
<label>Дата: <%= I18n.localize @event.date, format: :long %></label>
<div class="tiny button-group">
  <% if !EventsPolicy.new(current_user, @event).participant? %>
      <%= link_to 'Вступить', participant_path(@event), method: :post, class: 'button tiny' %>
  <% else %>
      <%= link_to 'Отписаться', delete_participant_path(@event, current_user), method: :delete, class: 'button tiny' %>
  <% end %>
  <%= link_to 'Стать докладчиком', new_event_application_path(@event), class: "button tiny" %>
</div>
<% if EventsPolicy.new(current_user, @event).access? %>
    <div class="tiny button-group">
      <%= link_to 'Редактировать', edit_event_path(@event), class: 'button tiny' %>
      <%= link_to 'Участники', participants_path, class: 'button tiny' %>
      <%= link_to 'Удалить', event_path(@event), method: :delete, class: 'alert button' %>
    </div>
<% end %>
<hr/>
<div class="new_post">
  <% if user_signed_in? && EventsPolicy.new(current_user, @event).access?%>
      <%= render 'posts/form' %>
  <% end %>
</div>
<div class="posts">
  <% @posts.reverse_order.each do |post| %>
      <%= render post %>
  <% end %>
</div>

app/views/events/show_participants.html.erb
<h2>Участники конференции</h2>
<div class="participant">
  <% @participants.each do |participant| %>
      <label>
        <%= link_to participant.user.first_name + " " + participant.user.last_name  , user_path(participant.user) %>
        <%= link_to '✖', delete_participant_path(@event, participant.user), method: :delete %>
      </label>
  <% end %>
</div>